# Generated by Django 3.0.5 on 2021-03-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StattricksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField()),
                ('process_ID', models.IntegerField()),
                ('process_sequence_ID', models.IntegerField()),
                ('series', models.IntegerField()),
                ('minimum_series', models.IntegerField()),
                ('minimum_series_datapoint', models.IntegerField()),
                ('minimum_continuous_datapoint', models.IntegerField()),
                ('process_hours', models.CharField(max_length=100)),
                ('values', models.IntegerField()),
            ],
        ),
    ]
